# Generated by Django 2.1.2 on 2020-10-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19genageinfo',
            name='createDt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='covid19info',
            name='createDt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='covid19sidoinfo',
            name='createDt',
            field=models.DateTimeField(null=True),
        ),
    ]
